### PR TITLE
Accommodate user-defined mirrors

### LINKED ISSUE #218: Generic instances for user-defined Mirror instances
Shapeless 3 currently does not work with user-defined instances of `scala.deriving.Mirror`. Usually, these instances are generated automatically by the compiler for ADTs, but it is actually possible to define your own instances. The need for such instances may arise for example in the context of structural refinement types and transparent def macros (To make a long story short: It is impossible with Scala 3 macros to define new types that escape the macro scope. A trick to circumvent this is to define a `Selectable` or `Dynamic` "stub" type and then add refinement type information through a transparent def macro and if you want that type to work with type-class derivation, you need to define your own `Mirror` instances). The reason that these custom instances don't work with Shapeless 3 is that Shapeless 3 does not use `Mirror` directly but instead `K0.Generic` and company, which are just refinements on `Mirror` to fix the kind:

```scala
type Generic[O] = Mirror {
  type Kind = K0.type
  type MirroredType = O
  type MirroredMonoType = O
  type MirroredElemTypes <: Tuple
}
```

As far as I can tell, these `Generic`/`Mirror` instances are not derived in code anywhere. It seems to me that they are generated by the compiler on-demand where they are used. The crux of the issue here is the additional `type Kind` refinement that is not present on `Mirror`: From my experiments, it appears that the compiler is happy to generate any arbitrary `Mirror { type FooBar = Noxarpe }` for you, no matter what `FooBar` is, but the type refinement will prevent regular `Mirror` instances coming from another place from being considered in the implicit search. If you `summon[Mirror.ProductOf[T]]` manually and try to plug it into a parameter of `K0.Generic[T]` it will not work. Letting the compiler generate the `Mirror { type Kind = K0.type }` in-place where a `K0.Generic[T]` is asked, will.

```scala
case class Beta(val a: Int, b: String)
K0.mkProductInstances[Show, Beta]   // works
K0.mkProductInstances[Show, Beta](using summon[K0.Generic[Beta]]) // works
K0.mkProductInstances[Show, Beta](using summon[Mirror.ProductOf[Beta] { type Kind = K0.type }]) // works
K0.mkProductInstances[Show, Beta](using summon[Mirror.ProductOf[Beta] {
  type Kind = K0.type
  type FooBar = Int
}]) // works
K0.mkProductInstances[Show, Beta](using summon[Mirror.ProductOf[Beta]]) // error
```

I propose to add a bunch of "implicit conversions" to the library to convert `Mirror` instances to `Generic` where necessary. Example:

```scala
inline given [T, MET <: Tuple, MEL <: Tuple](using inline m: Mirror.ProductOf[T] {
  type MirroredElemTypes = MET
  type MirroredElemLabels = MEL
}): (K0.ProductGeneric[T] {
  type Kind = K0.type
  type MirroredElemLabels = MEL
  type MirroredElemTypes = MET
  type MirroredType = T
  type MirroredMonoType = T
}) = m.asInstanceOf
```

Adding this given to the `Beta` example will make it compile correctly. My experiments suggest that the function and `m` parameter have to be inline and this Aux-pattern have to be used to make the compiler remember what `MirroredElemTypes` is concretely, or else uses of `Tuple.Size` and `LiftP` in Shapeless 3 will not work. Unfortunately, this means we can not write `& m.type` thus the types have to be spelled out for every `Generic`, `CoproductGeneric`, `ProductGeneric` for every `K` to make it work. Liberal use of inline givens in Shapeless 3 also prevents use of transparent inline here. 

Perhaps there is an easier way, but this is what I came up with. It is, of course, also possible to define your own `Generic` instances from the get-go whereever you are defining `Mirror`, but I'm not happy with that: It couples every library that wants to define their own types with custom `Mirror` instances to Shapeless, even when they don't depend on Shapeless themselves. It is also sometimes difficult to make sense of the error messages, especially when you don't know that you have to do it in the first place!

### PR DESCRIPTION
**Pull request by joroKr21**
Fixes #218

### CODE REVIEW

File: modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala [hunk 1]
```diff
@@ -315,28 +306,27 @@ object K1:
     inline def widen[G[t[_]] >: F[t]]: CoproductInstances[G, T] =
       inst.asInstanceOf
 
-  inline given mkInstances[F[_[_]], T[_]](using gen: Generic[T]): Instances[F, T] =
+  inline given mkInstances[F[_[_]], T[_]](using gen: Refl[Mirror, T]): Instances[F, T] =
```
Comment (tschuchortdev) [inline modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala:309]: Isn't this exactly the same as before? `Refl` still has the `type Kind` refinement and will thus exclude regular `Mirror`-instances from the implicit search that do not have this refinement.

File: modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala [hunk 2]
```diff
@@ -166,28 +158,27 @@ object K0:
     inline def widen[G[t] >: F[t]]: CoproductInstances[G, T] =
       inst.asInstanceOf
 
-  inline given mkInstances[F[_], T](using gen: Generic[T]): Instances[F, T] =
+  inline given mkInstances[F[_], T](using gen: Mirror.Of[T]): Instances[F, T] =
```
Comment (tschuchortdev) [inline modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala:161]: `K0.Generic`/`Refl` isn't actually used here anymore, that's why your test compiles for `show` despite the parameter only asking for a `Mirror`, thus lacking the `type Kind` refinement.

File: modules/deriving/src/test/scala/shapeless3/deriving/deriving.scala [hunk 3]
```diff
@@ -393,3 +393,25 @@ class DerivationTests:
...
+        K2.Refl[Mirror.Sum, F] {
+          type MirroredElemTypes[A, B] = (Either[A, B], (A, B))
+        }
+    ) = Bifunctor[F]
+
+    def functorK[Alg[_[_]]](using
+        K11.Refl[Mirror.Product, Alg] {
+          type MirroredElemTypes[F[_]] = (F[Int], String)
+        }
+    ) = FunctorK[Alg]
```
Comment (tschuchortdev) [inline modules/deriving/src/test/scala/shapeless3/deriving/deriving.scala:417]: I don't see how this is actually testing the issue from #218. By refining `Refl`, your parameter is still asking whoever is calling the function to provide a `Mirror { type Kind = ... }`, i.e. a shapeless-specific `ProductGeneric`, exactly the thing that we want to avoid. I think a more realistic test would be something like this:

```scala
class Foo(val i: Int, val s: String, val b: Boolean) extends Product {
   ... Product impl here
}

inline given Mirror.ProductOf[Foo] {
   // I expect that this will not work without spelling out all the overriden types in the given's type declaration and making it inline
   type MirroredType = Foo
   type MirroredMonoType = Foo
   type MirroredLabel = "Foo"
   type MirroredElemTypes = (Int, String, Boolean)
   type MirroredElemLabels = ("i", "s", "b")
} = new Mirror {
   // Note: No mention of `type Kind`, ProductGeneric or any other Shapeless specifics
   type MirroredType = Foo
   type MirroredMonoType = Foo
   type MirroredLabel = "Foo"
   type MirroredElemTypes = (Int, String, Boolean)
   type MirroredElemLabels = ("i", "s", "b")
   override def fromProduct = ...
}

summon[Show[Foo]] // should internally call K0.mkProductInstances, thus triggering an implicit search for K0.ProductGeneric[Foo]
```
and accordingly for `K2`, `K11`, and so on.

File: modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala [hunk 4]
```diff
@@ -166,28 +158,27 @@ object K0:
...
     ErasedProductInstances[K0.type, F[T], LiftP[F, gen.MirroredElemTypes]](gen)
 
-  inline given mkCoproductInstances[F[_], T](using gen: CoproductGeneric[T]): CoproductInstances[F, T] =
+  inline given mkCoproductInstances[F[_], T](using gen: Mirror.SumOf[T]): CoproductInstances[F, T] =
     ErasedCoproductInstances[K0.type, F[T], LiftP[F, gen.MirroredElemTypes]](gen): CoproductInstances[F, T]
 
 object K1:
-  type Kind[C, O[_]] = C {
-    type Kind = K1.type
+  type Refl[M, O[_]] = M {
```
Comment (tschuchortdev) [inline modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala:173]: What's the idea behind the name `Refl` here? Makes me think of `<:<.refl` and the likes. I think `Generic` was easier to understand for users (previously `mkInstances` mentioned only `Generic[O]` instead of `Kind[Mirror, O]`.

**Review by tschuchortdev — CHANGES_REQUESTED** [review]

File: modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala (hunk 2 above)
Comment (joroKr21) [reply modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala:161]: `type Generic[O] = Mirror.Of[O] { type Kind = K0.type }`
So `K0.Generic` is the same as `Mirror.Of` plus `type Kind` refinement (for implicit scope).
And `Refl` is the equivalent of `Mirror.Of` for higher kinds.

File: modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala (hunk 4 above)
Comment (joroKr21) [reply modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala:173]: `Refl` like reflection. Dunno, I also don't like the name `Kind` given that it also has a type member `Kind`. So what's the meaning of `Kind#Kind`? `Generic` is easier to understand but it has the problem you reported that custom mirrors don't work with `Generic`. Whereas they do work with `Refl`.

File: modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala (hunk 1 above)
Comment (joroKr21) [reply modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala:309]: No, it's not the same. `Refl` has no type member `Kind` (`Generic` has it).
```scala
  type Refl[M, O[_]] = M {
    type MirroredType[X] = O[X]
    type MirroredMonoType = O[Any]
    type MirroredElemTypes[_] <: Tuple
  }
```

Basically `Refl[Mirror, F]` is the equivalent of `Mirror.Of` for kind `F[_]`

Comment (joroKr21) [reply modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala:309]: For comparison here is the definition of `Mirror.Of`:
```scala
type Of[T] = Mirror {
  type MirroredType = T
  type MirroredMonoType = T
  type MirroredElemTypes <: Tuple
}
```

File: modules/deriving/src/test/scala/shapeless3/deriving/deriving.scala (hunk 3 above)
Comment (joroKr21) [reply modules/deriving/src/test/scala/shapeless3/deriving/deriving.scala:417]: I guess I can change the test to use `Mirror` directly, it will be a bit more verbose

File: modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala (hunk 1 above)
Comment (tschuchortdev) [reply modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala:309]: I see, you are right. `Generic` is then only needed for the extension methods that you mentioned?

File: modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala (hunk 4 above)
Comment (tschuchortdev) [reply modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala:173]: I agree that `Kind` is not a great name either. How about something like `type FixMirrorKind[M <: Mirror, O[_]]`? Also it should be mentioned that changing the name, as well as removing `type Kind` is technically a breaking change in public API, though unlikely to cause much trouble.

File: modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala (hunk 1 above)
Comment (joroKr21) [reply modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala:309]: I believe so, yeah

File: modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala [hunk 5]
```diff
@@ -22,19 +22,11 @@ import scala.Tuple.Union
...
-
-  type Generic[O] = Kind[Mirror, O]
-  type ProductGeneric[O] = Kind[Mirror.Product, O]
-  type CoproductGeneric[O] = Kind[Mirror.Sum, O]
+  type Generic[O] = Mirror.Of[O] { type Kind = K0.type }
+  type ProductGeneric[O] = Mirror.ProductOf[O] { type Kind = K0.type }
+  type CoproductGeneric[O] = Mirror.SumOf[O] { type Kind = K0.type }
 
   def Generic[O](using gen: Generic[O]): gen.type = gen
   def ProductGeneric[O](using gen: ProductGeneric[O]): gen.type = gen
```
Comment (tschuchortdev) [inline modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala:32]: So far I have only interacted with Shapeless 3 through the `ProductInstances`, so I didn't consider this in the original issue #218, but I suspect that these methods as well as `Generic.derive` (which I can not comment on due to Github's broken UI), will suffer from the same problem as `mkInstances`. If `Generic.derive` is supposed to be an entry point in the library like in Magnolia, then it will not work correctly with custom `Mirror` instances since `Generic` still retains the `type Kind` refinement. `def Generic[O](using gen: Generic[O]): gen.type = gen` could probably be changed here to `def Generic[O](using m: Refl[Mirror, O]): Generic[O] & m.type = m.asInstanceOf` (inlining may be necessary), but this would only help if the user is summoning `Generic[O]` through `def Generic`. If the user is summoning `Generic[O]` through implicit search via an implicit parameter, it will not find plain `Mirror` instances.  In this light, I feel like the implicit conversions are still the most robust solution, as they will work in every case automatically. It's pretty much what you'd end up writing to derive `Generic` if it was a new type and not just a refinement on `Mirror`.

**Review by tschuchortdev — CHANGES_REQUESTED** [review]

File: modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala (hunk 4 above)
Comment (joroKr21) [reply modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala:173]: But then what does `FixMirrorKind[Mirror, Option]` mean? Btw, adding a bound `M <: Mirror` would be a binary-breaking change, whereas changing the type alias is only source-breaking (if anyone is using it at all, I struggle to think of a use-case for it outside the library). I guess I could add back the `Kind` type alias and it would be also source-compatible.

File: modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala (hunk 5 above)
Comment (joroKr21) [reply modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala:32]: `Generic.derive` is one of the extension methods I mentioned that needs the implicit scope of `type Kind`. I will look into changing `def Generic`. But an implicit conversion will not help with the extension methods and with the implicit scope.

Comment (tschuchortdev) [reply modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala:32]: Why not? Note that in Scala 3, implicit conversions are specifically givens of type `Conversion[?,?]`, so strictly speaking my suggestion is not a real implicit conversion, just a regular ol' derivation. `Conversion`s are not considered during implicit search iirc, but the given from #218 should work fine. 

This is the situation I'm talking about:
```scala
def myDerivation(using g: Generic[Foo]) {
    g.derive(...)
}
```
as opposed to
```scala
def myDerivation(using Mirror[Foo]) {
    Generic.derive(...)
}
```
which should work after changing `def Generic` to depend on `Mirror`.

I suspect that `def Generic` will require the same inlining and Aux tricks and end up looking identical to my example from #218, except as a def instead of given.

Comment (joroKr21) [reply modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala]: Dunno, seems to work simply by changing the type signature. If we define implicit conversions, they would have to be imported which is poor UX and a bigger change than the type alias.

File: modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala (hunk 4 above)
Comment (tschuchortdev) [reply modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala]: Yeah, it doesn't read well, but it's still more meaningful, don't you think? 

`(Mirror WithKind K0)[Option]` would be nice.
```scala 3
sealed trait Kinds
object K1 extends Kinds {
  ...
}

infix type WithKind[M <: Mirror, K <: Kinds] = K match {
    case K1 => [O[_]] =>> M {
       type MirroredType[X] = O[X]
       ...
    }
    ... 
}
```
Probably binary incompatible as well. I'm just brainstorming. But it's only a name, so no reason to bikeshed.

File: modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala (hunk 5 above)
Comment (tschuchortdev) [reply modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala]: With "changing the type signature" do you mean the signature of `myDerivation`? My point is that both `myDerivation` and `Foo` may be in different third-party libraries, so neither the definition of `myDerivation` nor `Mirror[Foo]` can easily be changed by the enduser. They would have to essentially wrap the `Mirror[Foo]` themselves with a given like I've shown in #218 _or_ manually provide the implicit parameter at every use-site and cast it: `given MyDerived = myDerivation(using summon[Mirror.Of[Foo]].asInstanceOf[Generic[Foo]])`. 

If the implicit conversions were in a companion object to `Generic`, wouldn't they be available automatically? I'm not so familiar with the implicit resolution rules. We could also leave the `Generic` parameter in `mkInstances`  and try to provide a hint with `@implicitNotFound` that directs users to import the implicit conversions if their type has a custom `Mirror` instance. The question then is how to incorporate the regular error message for non-case-classes.

Comment (joroKr21) [reply modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala]: I meant changing the signature of `def Generic`. `type Generic` is just a type alias so it has no companion object. Maybe it would have been better to make it an opaque type but idk if that would be binary compatible.

Comment (tschuchortdev) [reply modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala]: But if you only change `def Generic` it won't fix the `myDerivation` example?

Comment (joroKr21) [reply modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala]: I'm not sure I understand, what is not fixed exactly?

File: modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala (hunk 4 above)
Comment (joroKr21) [reply modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala]: Infix type sounds interesting, perhaps `Mirror of O`, `Mirror.Product of O` and `Mirror.Sum of O`

File: modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala (hunk 5 above)
Comment (tschuchortdev) [reply modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala]: If I'm not mistaken this still won't work, even if you change `def Generic`:
```scala
def myDerivation(using g: Generic[Foo]) {
    g.derive(...)
}
```
If this is the derivation code in some third-party library, then the end-user can not change the signature of `myDerivation` and is out of luck (not to mention that even if they could, the standard error message would not be particularly helpful for them to figure that out).

File: modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala (hunk 4 above)
Comment (joroKr21) [reply modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala]: Hmm, I think `M <: Mirror` was giving me mima errors because I didn't clean, it might be actually ok.

Comment (tschuchortdev) [reply modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala]: We already have `Mirror.Of[O]` though. Could be confusing, too.

Comment (joroKr21) [reply modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala]: Not for higher kinds, we don't have it

Comment (tschuchortdev) [reply modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala]: The name is very similar, I mean.

File: modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala (hunk 5 above)
Comment (joroKr21) [reply modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala]: But an implicit conversion would not fix that either

Comment (tschuchortdev) [reply modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala]: Why not? I don't see how `myDerivation` is different in that respect from `K0.mkProductInstances`, which I have confirmed to work. When `myDerivation` is called, it will look for givens of type `Generic[Foo]` in scope at the use site. It will then find the "implicit conversion" given from #218, look in turn for an instance of `Mirror.Of[T]` and find it. The conversion givens must be somehow imported, of course.

Comment (joroKr21) [reply modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala:41]: No, implicit conversions don't work like that. I've added a normal given, also seems to work.

File: modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala (hunk 4 above)
Comment (joroKr21) [reply modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala]: It serves the same purpose

File: modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala (hunk 5 above)
Comment (tschuchortdev) [reply modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala:41]: But it isn't an implicit conversion, strictly speaking. Your given works exactly the same as mine, except it doesn't seem to need the inline and Aux stuff to remember the concrete Tuple types.

Comment (joroKr21) [reply modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala:41]: Ok, I just got confused by the entire talk about implicit conversions. So you were suggesting to add a given. It makes sense now, this has nothing to do with implicit conversions. 

> Your given works exactly the same as mine, except it doesn't seem to need the inline and Aux stuff to remember the concrete Tuple types, unless the test is somehow not testing it sufficiently.

`m.type` makes sure the type is preserved.

**Comment by joroKr21** [comment]
@tschuchortdev I tried this out in [Kittens](https://github.com/typelevel/kittens) and unfortunately it degrades compiler performance significantly (`rootJVM/Test/compile` went from ~30s to ~60s). So I think we will have to put it behind an import after all.

**Comment by tschuchortdev** [comment]
Oh, that's too bad, but I guess it can't be avoided. Have you thought about putting an `@implicitNotFound` on `Generic` parameters to direct the user towards the import? I've just experimented with it a little bit and it seems that the custom error message is simply prepended to the compiler's message "failed to synthesize Generic because Foo is not a case class", meaning the error messages will not be worse in other cases if we add our own hint.

**Comment by joroKr21** [comment]
Yes, this would make sense. Although I'm still waiting for a backport of `@implicitNotFound` for type aliases: https://github.com/scala/scala3/pull/20275

File: modules/deriving/src/test/scala/shapeless3/deriving/deriving.scala [hunk 6]
```diff
@@ -393,3 +393,52 @@ class DerivationTests:
...
     assertEquals(Left("Missing field 's';"), parser.parseShort("i=42,b=kinda"))
     assertEquals(Left("Invalid field 'broken';"), parser.parseShort("i=42,broken,?"))
+
+  @Test
+  def userDefinedMirrors(): Unit =
+    def assertImportSuggested(errors: List[testing.Error]): Unit =
+      assertEquals(1, errors.size)
+      val message = errors.head.message.trim
+      assert(message.startsWith("No given instance of type"))
+      assert(message.endsWith("Generic.fromMirror"))
```
Comment (joroKr21) [inline modules/deriving/src/test/scala/shapeless3/deriving/deriving.scala:403]: @tschuchortdev the default message already suggests the import so I think it's adequate

Comment (tschuchortdev) [reply modules/deriving/src/test/scala/shapeless3/deriving/deriving.scala:403]: Alright. In my experience those suggestions are rarely productive, so I tend to ignore them.

**Comment by tschuchortdev** [comment]
Looks good to me now.
